In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
a = np.array([ 1, 2, 3, 4])

In [ ]:
two_dim = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
three_dim = np.array(
[[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
],
[
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
]]
)

In [ ]:
a * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
b = []
for i in a:
  b.append(i*2)
b

[2, 4, 6, 8]

In [ ]:
c = np.array([1, 2, 3, 4])


In [ ]:
two_dim.std

<function ndarray.std>

In [ ]:
a.dtype, a.size, a.shape, a.ndim

(dtype('int64'), 4, (4,), 1)

In [ ]:
two_dim.ndim, two_dim.dtype, two_dim.size, two_dim.shape

(2, dtype('int64'), 9, (3, 3))

In [ ]:
np.random.seed(42)
np.random.randint(1, 100, size = (5, 3))

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24],
       [ 3, 22, 53]])

In [ ]:
arr1=np.array(
    [
        [2, 4, 7, 4],
        [3, 9, 12, 7]
    ]
)

In [ ]:
arr2=np.array(
    [
        [3, 6],
        [5, 9],
        [7, 3],
        [3,6]
    ]
)

In [ ]:
arr3=np.array(
    [
     [13, 9, 61, 12],
     [17, 11, 18, 17],
     [96, 27, 13, 56]
    ]
  )

In [ ]:
np.dot(arr1, arr2)

array([[ 87,  93],
       [159, 177]])

In [ ]:
np.matmul(arr1, arr2)

array([[ 87,  93],
       [159, 177]])

In [ ]:
arr1 @ arr2

array([[ 87,  93],
       [159, 177]])

In [ ]:
np.sqrt(21404)

146.30105946301276

In [ ]:
three_dim.dtype

dtype('int64')

In [ ]:
two_dim.dtype

dtype('int64')

In [ ]:
np.ones(shape = (10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
three_dim[1][2][0]

16

In [ ]:
np.zeros(shape= (7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.arange(0, 101, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
np.random.randint(0, 10, (7,2))

array([[1, 7],
       [5, 1],
       [4, 0],
       [9, 5],
       [8, 0],
       [9, 2],
       [6, 3]])

In [ ]:
np.random.random((3,5))

array([[0.9429097 , 0.32320293, 0.51879062, 0.70301896, 0.3636296 ],
       [0.97178208, 0.96244729, 0.2517823 , 0.49724851, 0.30087831],
       [0.28484049, 0.03688695, 0.60956433, 0.50267902, 0.05147875]])

In [ ]:
np.random.uniform(5,6, (3,5))

array([[5.14489487, 5.48945276, 5.98565045, 5.24205527, 5.67213555],
       [5.76161962, 5.23763754, 5.72821635, 5.36778313, 5.63230583],
       [5.63352971, 5.53577468, 5.09028977, 5.8353025 , 5.32078006]])

In [ ]:
np.random.seed(42)
np.random.randint(0, 10, (4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
random_array = np.random.randint(1, 10, (3,7))
print(random_array)

[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]


In [ ]:
unique_values = np.unique(random_array)
print(unique_values)

[1 2 3 4 5 7 9]


In [ ]:
print(random_array[0])

[9 1 3 7 4 9 3]


In [ ]:
slice_arr = random_array[:2]
print(slice_arr)

[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]]


In [ ]:
val_2row=slice_arr[:2, :2]
print(val_2row)

[[4 7]
 [4 1]]


In [ ]:
np.random.randint(1, 10 ,(3,5))


array([[8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1],
       [5, 7, 9, 7, 9]])

In [ ]:
n=np.ones(shape=(3,5))

In [ ]:
result=np.vstack((r,n))

In [ ]:
np.dot(r, n)


ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)